### ISSUE TITLE
request for 3DOF to make a comeback

### ISSUE THREAD

**Issue by Zeleny278** [stsichler/portal_reloaded_vr#2]
I'm one of the weirdos that like 3DOF for portal 2 since it makes going through a portal more consistent (no need to click left joystick, no chance of a flicker while going through + never hitting the wall instead of portal due to misalignement)

If it's troublesome to add or straight impossible, I understand and I want to add I am already very thankful that you made this game available in VR.

**Comment by stsichler** [comment]
I'm not exactly sure what you mean. But maybe the `SeatedMode` Option in the config file helps?

**Comment by stsichler** [comment]
Ok, I now do understand. This is fixed by cb7df6f0453e1fa1040a1d56bbd7b741d881d052, see [Release v0.2.0p1-reloaded.3](https://github.com/stsichler/portal_reloaded_vr/releases/tag/v0.2.0p1-reloaded.3)
